# Generated by Django 6.0 on 2025-12-20 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mandataire", "0001_initial"),
        ("organisme", "0001_initial"),
        ("reseaux", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fiche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duree_mandat",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Durée du mandat"
                    ),
                ),
                (
                    "frequence_reunions",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Fréquence des réunions",
                    ),
                ),
                (
                    "maintien_salaire",
                    models.BooleanField(
                        default=False, verbose_name="Maintien de salaire"
                    ),
                ),
                (
                    "frais_kms",
                    models.BooleanField(
                        default=False, verbose_name="Frais kilométriques"
                    ),
                ),
                (
                    "restauration",
                    models.BooleanField(
                        default=False, verbose_name="Frais de restauration"
                    ),
                ),
                (
                    "hebergement",
                    models.BooleanField(default=False, verbose_name="Hébergement"),
                ),
                (
                    "missions_mandataire",
                    models.TextField(blank=True, verbose_name="Missions du mandataire"),
                ),
                (
                    "temps_investi",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Temps investi dans les mandats",
                    ),
                ),
                (
                    "profil_mandataire",
                    models.TextField(blank=True, verbose_name="Profil du mandataire"),
                ),
                (
                    "institutions_env_mandat",
                    models.TextField(
                        blank=True,
                        verbose_name="Institutions dans l'environnement du mandat",
                    ),
                ),
                (
                    "type_mandat",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Type de mandat"
                    ),
                ),
                (
                    "principales_activites",
                    models.TextField(
                        blank=True, verbose_name="Principales activités du mandataire"
                    ),
                ),
                (
                    "competences",
                    models.TextField(blank=True, verbose_name="Compétences"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "date_modification",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "mandataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fiches",
                        to="mandataire.mandataire",
                        verbose_name="Mandataire",
                    ),
                ),
                (
                    "organisme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fiches",
                        to="organisme.organisme",
                        verbose_name="Organisme",
                    ),
                ),
                (
                    "reseau",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fiches",
                        to="reseaux.reseau",
                        verbose_name="Thématique (Réseau)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiche Mandascop",
                "verbose_name_plural": "Fiches Mandascop",
                "ordering": ["-date_creation"],
            },
        ),
    ]
