# Generated by Django 6.0 on 2025-12-19 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mandascop", "0001_initial"),
        ("mandataire", "0001_initial"),
        ("organisme", "0001_initial"),
        ("reseaux", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiche",
            name="mandataire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fiches",
                to="mandataire.mandataire",
                verbose_name="Mandataire",
            ),
        ),
        migrations.AddField(
            model_name="fiche",
            name="organisme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fiches",
                to="organisme.organisme",
                verbose_name="Organisme",
            ),
        ),
        migrations.AddField(
            model_name="fiche",
            name="reseau",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fiches",
                to="reseaux.reseau",
                verbose_name="Thématique (Réseau)",
            ),
        ),
    ]
