# Generated by Django 6.0 on 2025-12-19 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mandascop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mandat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_mandat",
                    models.CharField(
                        choices=[
                            ("titulaire", "Titulaire"),
                            ("suppleant", "Suppléant"),
                        ],
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "date_modification",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "fiche_mandascop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mandats",
                        to="mandascop.fiche",
                        verbose_name="Fiche Mandascop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mandat",
                "verbose_name_plural": "Mandats",
                "ordering": ["militant", "organisme"],
            },
        ),
    ]
