# Generated by Django 6.0 on 2025-12-19 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mandat", "0001_initial"),
        ("mandataire", "0001_initial"),
        ("organisme", "0001_initial"),
        ("reseaux", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mandat",
            name="mandataire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mandats",
                to="mandataire.mandataire",
                verbose_name="Mandataire",
            ),
        ),
        migrations.AddField(
            model_name="mandat",
            name="militant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mandats",
                to="user.militant",
                verbose_name="Militant",
            ),
        ),
        migrations.AddField(
            model_name="mandat",
            name="organisme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mandats",
                to="organisme.organisme",
                verbose_name="Organisme",
            ),
        ),
        migrations.AddField(
            model_name="mandat",
            name="reseau",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mandats",
                to="reseaux.reseau",
                verbose_name="Réseau",
            ),
        ),
    ]
