# Generated by Django 6.0 on 2025-12-19 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adresse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rue", models.CharField(max_length=255, verbose_name="Rue")),
                (
                    "code_postal",
                    models.CharField(max_length=10, verbose_name="Code postal"),
                ),
                ("ville", models.CharField(max_length=150, verbose_name="Ville")),
            ],
            options={
                "verbose_name": "Adresse",
                "verbose_name_plural": "Adresses",
            },
        ),
        migrations.CreateModel(
            name="Reseau",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Exemples : Santé au travail, Handicap, Sécurité sociale, Emploi Formation",
                        max_length=150,
                        unique=True,
                        verbose_name="Nom",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "date_modification",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
            ],
            options={
                "verbose_name": "Réseau",
                "verbose_name_plural": "Réseaux",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Organisme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "objet",
                    models.CharField(
                        help_text="Objet ou mission principale de l’organisme",
                        max_length=255,
                        verbose_name="Objet",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "mail",
                    models.EmailField(max_length=254, verbose_name="Adresse email"),
                ),
                (
                    "telephone",
                    models.CharField(max_length=30, verbose_name="Téléphone"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "date_modification",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "adresse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organismes",
                        to="organisme.adresse",
                        verbose_name="Adresse",
                    ),
                ),
                (
                    "reseau",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organismes",
                        to="organisme.reseau",
                        verbose_name="Reseau",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisme",
                "verbose_name_plural": "Organismes",
                "ordering": ["nom"],
            },
        ),
    ]
