# Generated by Django 6.0 on 2025-12-19 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisme", "0001_initial"),
        ("reseaux", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisme",
            name="reseau",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organismes",
                to="reseaux.reseau",
                verbose_name="Reseau",
            ),
        ),
        migrations.DeleteModel(
            name="Reseau",
        ),
    ]
