# Generated by Django 6.0 on 2025-12-20 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organisme", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mandataire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom du mandataire ou de la structure",
                        max_length=255,
                        verbose_name="Nom",
                    ),
                ),
                (
                    "structure",
                    models.CharField(
                        choices=[
                            ("UL", "Union Locale (UL)"),
                            ("UD", "Union Départementale (UD)"),
                            ("UR", "Union Régionale (UR)"),
                            ("FEDERATION", "Fédération"),
                            ("CONFEDERATION", "Confédération"),
                            ("SYNDICAT", "Syndicat"),
                        ],
                        max_length=20,
                        verbose_name="Structure",
                    ),
                ),
                (
                    "mail",
                    models.EmailField(max_length=254, verbose_name="Adresse email"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "date_modification",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "adresse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mandataires",
                        to="organisme.adresse",
                        verbose_name="Adresse postale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mandataire",
                "verbose_name_plural": "Mandataires",
                "ordering": ["structure", "nom"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("nom", "structure"),
                        name="unique_mandataire_nom_structure",
                    )
                ],
            },
        ),
    ]
