# Generated by Django 6.0 on 2025-12-21 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mandataire", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adresse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rue",
                    models.CharField(max_length=255, verbose_name="Adresse ligne 1"),
                ),
                (
                    "code_postal",
                    models.CharField(max_length=5, verbose_name="Code postal"),
                ),
                ("ville", models.CharField(max_length=100, verbose_name="Ville")),
            ],
            options={
                "verbose_name": "Adresse",
                "verbose_name_plural": "Adresses",
                "ordering": ["ville", "code_postal", "rue"],
            },
        ),
        migrations.AlterField(
            model_name="mandataire",
            name="adresse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mandataires",
                to="mandataire.adresse",
                verbose_name="Adresse postale",
            ),
        ),
    ]
