# Generated by Django 6.0 on 2025-12-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Militant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150, verbose_name="Nom")),
                ("prenom", models.CharField(max_length=150, verbose_name="Prénom")),
                (
                    "mail",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "a_jour_cotisation",
                    models.BooleanField(
                        default=False, verbose_name="À jour de cotisation"
                    ),
                ),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Féminin")],
                        max_length=1,
                        verbose_name="Sexe",
                    ),
                ),
                (
                    "annee_naissance",
                    models.PositiveSmallIntegerField(verbose_name="Année de naissance"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "date_modification",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
            ],
            options={
                "verbose_name": "Militant",
                "verbose_name_plural": "Militants",
                "ordering": ["nom", "prenom"],
            },
        ),
    ]
